spring:
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

jwt:
  secret: dGVzdC1zZWNyZXQta2V5LXRlc3Qtc2VjcmV0LWtleQ==y


eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
